config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  root to: "projects#index"
  resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    validates_presence_of :title, :description
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_student!, except: [:index, :show]
  
  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cs3300</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    

    

  </head>


  <body>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-6 col-md-6 py-4">
              <h4 class="text-white">About Me</h4>
              <p class="text-muted">I'm a computer engineering graduate from UCCS! I have a passion for technology and progress. Currently, I am pursuing a masters to work with and innovate on VR and AR devices. I want to be a part of the future and I know I can help shape it through work in these technologies. Deep learning, AI, embedded systems, and quantum computing are some of my other areas of current major intrest.</p>
            </div>
            <div class="col-sm-4 offset-md-2 py-4">
              <h4 class="text-white">Contact Me</h4>
              <ul class="list-unstyled">
                <li class="text-white">Nbuckleyce@gmail.com</li>
                <li><a href="https://github.com/Nilawafers" class="text-white">My Github</a></li>
                <li class="text-white">Xbox GT Nilafacekiller ;D</li>
              </ul>
            </div>
            
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="/" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M20 9v11a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V9"/><path d="M9 22V12h6v10M2 10.6L12 2l10 8.6"/></svg>
            <strong>Home</strong>
          </a>

          <ul class="nav nav-pills" >
            <% if student_signed_in? %>
              <li class="nav-item active"  style="text-shadow: 1px 1px black;">
                <a class="nav-link" style="color: white;" href="/students/edit">Account</a>
              </li>
              <li class="nav-item active"  style="text-shadow: 1px 1px black;">
                <a class="nav-link" style="color: white;" href="/students/sign_out">Sign Out</a>
              </li>
              
            <% else %>
              <li class="nav-item active"  style="text-shadow: 1px 1px black;">
                <a class="nav-link" style="color: white;" href="/students/sign_up">Sign Up</a>
              </li>
              <li class="nav-item active"  style="text-shadow: 1px 1px black;">
                <a class="nav-link" style="color: white;" href="/students/sign_in">Sign In</a>
              </li>
            <% end %>
          </ul>


          
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
  </header>

    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <center>

  <div class="field">
    <h5><%= form.label :title %></h5>
    
    <%= form.text_field :title %>
    
  
  </div>

  
  <div class="field">
    <h5><%= form.label :description %></h5>
    <%= form.text_area :description %>
  </div>
  

  <div class="actions">
    <%= form.submit %>
  </div>
  </center>
<% end %>

app/views/projects/edit.html.erb
<center>
<h1>Editing Project</h1>


<%= render 'form', project: @project %>


<%= link_to "<button type='button' class='btn btn-sm btn-outline-secondary'>Back</button>".html_safe, projects_path %>

<% if student_signed_in? %>
  <%= link_to "<button type='button' class='btn btn-sm btn-outline-secondary'>Show</button>".html_safe, @project %>
<% end %>
</center>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron" style="background-color:white;margin-bottom:0%;padding-bottom:0px">
<div class="container">
    <h1 class="display-5 ">Welcome to Nicholas Buckley's portfolio site!</h1>
    <p>Here anyone can see projects posted and account owners can add, edit, or delete any project they want. Thanks for stopping by today!</p>
</div>
</div>

<center><h2>Projects</h2></center>


<table>

  <tbody>
  <div class="Projects py-5 bg-light">
        <div class="container">

          <div class="row">
            
            
          
            <% @projects.each do |project| %>
              
              <div class="col-md-4">
                <div class="card mb-4 box-shadow text-center">
                  <div class="card-header"><h6> <%= project.title %></h6> </div>
                  <div class="card-body">
                    <p  class="card-text text-truncate" > <%= project.description %></p>
                    <div class="d-flex justify-content-between align-items-center">
                      <div class="btn-group">
                        <%= link_to "<button type='button' class='btn btn-sm btn-outline-secondary'>Show</button>".html_safe, project %>
                        <% if student_signed_in? %>
                          <a  href=<%= edit_project_path(project) %> >
                            <button type="button" class="btn btn-sm btn-outline-secondary" >Edit</button>
                          </a>
                          <%= link_to "<button type='button' class='btn btn-sm btn-outline-secondary'>Destroy</button>".html_safe, project, method: :delete, data: { confirm: 'Are you sure?' } %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

            <% end %>
            <% if student_signed_in? %>
              <div class="col-md-4">
                <div class="card mb-4 box-shadow text-center" >
                  <div class="card-header"><h6>{Project Title}</h6></div>
                  <div class="card-body">
                    <p class="card-text">{Project Description}</p>
                    <div class="d-flex  align-items-center">
                    
                      <%= link_to "<button type='button' class='btn btn-sm btn-outline-secondary'>Create New Project</button>".html_safe, new_project_path %>
                    
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </tbody>
</table>

<br>

app/views/projects/new.html.erb
<center><h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to "<button type='button' class='btn btn-sm btn-outline-secondary'>Back</button>".html_safe, projects_path %>
</center>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<center>


<div class="Projects py-5 bg-light">
      <div class="container">
        <div class="col-md-12">
          <div class="card mb-12 box-shadow text-center">
            <div class="card-header"> <h4><%= @project.title %></h4> </div>
            <div class="card-body">
              <p  class="card-text" > <%= @project.description %></p>
              <div class="d-flex justify-content-between align-items-center">
                
              </div>
            </div>
          </div>
        </div>
      </div>
    
    </div>
  </div>





<%= link_to "<button type='button' class='btn btn-sm btn-outline-secondary'>Back</button>".html_safe, projects_path %>

<% if student_signed_in? %>
  <%= link_to "<button type='button' class='btn btn-sm btn-outline-secondary'>Edit</button>".html_safe, edit_project_path(@project) %>
<% end %>
</center>

app/views/students/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/students/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>